// <auto-generated>
// This code was generated by Maui.ColorResourcesGenerator
// Generated on: 2025-10-22 21:52:07
// Do not edit this file manually - changes will be overwritten!
// </auto-generated>

#nullable enable

namespace AppoMobi.Maui.DrawnUi.Demo
{
    /// <summary>
    /// Exception thrown when a color resource cannot be found in the application resources.
    /// </summary>
    public class ColorResourceNotFoundException : System.Exception
    {
        /// <summary>
        /// Initializes a new instance of ColorResourceNotFoundException.
        /// </summary>
        /// <param name="colorKey">The key of the color resource that was not found.</param>
        public ColorResourceNotFoundException(string colorKey)
            : base($"Color resource '{colorKey}' not found in application resources. Ensure Colors.xaml is properly loaded.")
        {
            ColorKey = colorKey;
        }

        /// <summary>
        /// Gets the key of the color resource that was not found.
        /// </summary>
        public string ColorKey { get; }
    }

    /// <summary>
    /// Auto-generated fluent helper class for accessing color resources from Colors.xaml
    /// </summary>
    public static class AppColors
    {
        #region Standard Colors

        private static Microsoft.Maui.Graphics.Color? _black;
        /// <summary>
        /// Color resource: Black (Black)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Black
        {
            get
            {
                if (_black == null)
                {
                    _black = Microsoft.Maui.Controls.Application.Current?.Resources["Black"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Black");
                }
                return _black;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _white;
        /// <summary>
        /// Color resource: White (White)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color White
        {
            get
            {
                if (_white == null)
                {
                    _white = Microsoft.Maui.Controls.Application.Current?.Resources["White"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("White");
                }
                return _white;
            }
        }

        #endregion

        #region Gray Scale Colors

        private static Microsoft.Maui.Graphics.Color? _gray100;
        /// <summary>
        /// Color resource: Gray100 (#E1E1E1)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray100
        {
            get
            {
                if (_gray100 == null)
                {
                    _gray100 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray100"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray100");
                }
                return _gray100;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray200;
        /// <summary>
        /// Color resource: Gray200 (#C8C8C8)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray200
        {
            get
            {
                if (_gray200 == null)
                {
                    _gray200 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray200"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray200");
                }
                return _gray200;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray300;
        /// <summary>
        /// Color resource: Gray300 (#ACACAC)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray300
        {
            get
            {
                if (_gray300 == null)
                {
                    _gray300 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray300"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray300");
                }
                return _gray300;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray400;
        /// <summary>
        /// Color resource: Gray400 (#919191)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray400
        {
            get
            {
                if (_gray400 == null)
                {
                    _gray400 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray400"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray400");
                }
                return _gray400;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray500;
        /// <summary>
        /// Color resource: Gray500 (#6E6E6E)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray500
        {
            get
            {
                if (_gray500 == null)
                {
                    _gray500 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray500"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray500");
                }
                return _gray500;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray600;
        /// <summary>
        /// Color resource: Gray600 (#404040)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray600
        {
            get
            {
                if (_gray600 == null)
                {
                    _gray600 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray600"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray600");
                }
                return _gray600;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray900;
        /// <summary>
        /// Color resource: Gray900 (#212121)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray900
        {
            get
            {
                if (_gray900 == null)
                {
                    _gray900 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray900"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray900");
                }
                return _gray900;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _gray950;
        /// <summary>
        /// Color resource: Gray950 (#141414)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Gray950
        {
            get
            {
                if (_gray950 == null)
                {
                    _gray950 = Microsoft.Maui.Controls.Application.Current?.Resources["Gray950"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Gray950");
                }
                return _gray950;
            }
        }

        #endregion

        #region Accent Colors

        private static Microsoft.Maui.Graphics.Color? _blue100Accent;
        /// <summary>
        /// Color resource: Blue100Accent (#3E8EED)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Blue100Accent
        {
            get
            {
                if (_blue100Accent == null)
                {
                    _blue100Accent = Microsoft.Maui.Controls.Application.Current?.Resources["Blue100Accent"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Blue100Accent");
                }
                return _blue100Accent;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _blue200Accent;
        /// <summary>
        /// Color resource: Blue200Accent (#72ACF1)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Blue200Accent
        {
            get
            {
                if (_blue200Accent == null)
                {
                    _blue200Accent = Microsoft.Maui.Controls.Application.Current?.Resources["Blue200Accent"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Blue200Accent");
                }
                return _blue200Accent;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _blue300Accent;
        /// <summary>
        /// Color resource: Blue300Accent (#A7CBF6)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Blue300Accent
        {
            get
            {
                if (_blue300Accent == null)
                {
                    _blue300Accent = Microsoft.Maui.Controls.Application.Current?.Resources["Blue300Accent"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Blue300Accent");
                }
                return _blue300Accent;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _cyan100Accent;
        /// <summary>
        /// Color resource: Cyan100Accent (#28C2D1)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Cyan100Accent
        {
            get
            {
                if (_cyan100Accent == null)
                {
                    _cyan100Accent = Microsoft.Maui.Controls.Application.Current?.Resources["Cyan100Accent"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Cyan100Accent");
                }
                return _cyan100Accent;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _cyan200Accent;
        /// <summary>
        /// Color resource: Cyan200Accent (#7BDDEF)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Cyan200Accent
        {
            get
            {
                if (_cyan200Accent == null)
                {
                    _cyan200Accent = Microsoft.Maui.Controls.Application.Current?.Resources["Cyan200Accent"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Cyan200Accent");
                }
                return _cyan200Accent;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _cyan300Accent;
        /// <summary>
        /// Color resource: Cyan300Accent (#C3F2F4)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Cyan300Accent
        {
            get
            {
                if (_cyan300Accent == null)
                {
                    _cyan300Accent = Microsoft.Maui.Controls.Application.Current?.Resources["Cyan300Accent"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Cyan300Accent");
                }
                return _cyan300Accent;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _yellow100Accent;
        /// <summary>
        /// Color resource: Yellow100Accent (#F7B548)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Yellow100Accent
        {
            get
            {
                if (_yellow100Accent == null)
                {
                    _yellow100Accent = Microsoft.Maui.Controls.Application.Current?.Resources["Yellow100Accent"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Yellow100Accent");
                }
                return _yellow100Accent;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _yellow200Accent;
        /// <summary>
        /// Color resource: Yellow200Accent (#FFD590)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Yellow200Accent
        {
            get
            {
                if (_yellow200Accent == null)
                {
                    _yellow200Accent = Microsoft.Maui.Controls.Application.Current?.Resources["Yellow200Accent"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Yellow200Accent");
                }
                return _yellow200Accent;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _yellow300Accent;
        /// <summary>
        /// Color resource: Yellow300Accent (#FFE5B9)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color Yellow300Accent
        {
            get
            {
                if (_yellow300Accent == null)
                {
                    _yellow300Accent = Microsoft.Maui.Controls.Application.Current?.Resources["Yellow300Accent"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("Yellow300Accent");
                }
                return _yellow300Accent;
            }
        }

        #endregion

        #region Custom Colors

        private static Microsoft.Maui.Graphics.Color? _colorAccent;
        /// <summary>
        /// Color resource: ColorAccent (#FF0000)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorAccent
        {
            get
            {
                if (_colorAccent == null)
                {
                    _colorAccent = Microsoft.Maui.Controls.Application.Current?.Resources["ColorAccent"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorAccent");
                }
                return _colorAccent;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _colorAccentLight;
        /// <summary>
        /// Color resource: ColorAccentLight (#FF8F8F)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorAccentLight
        {
            get
            {
                if (_colorAccentLight == null)
                {
                    _colorAccentLight = Microsoft.Maui.Controls.Application.Current?.Resources["ColorAccentLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorAccentLight");
                }
                return _colorAccentLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _colorDanger;
        /// <summary>
        /// Color resource: ColorDanger (#FF5F5F)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorDanger
        {
            get
            {
                if (_colorDanger == null)
                {
                    _colorDanger = Microsoft.Maui.Controls.Application.Current?.Resources["ColorDanger"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorDanger");
                }
                return _colorDanger;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _colorPaper;
        /// <summary>
        /// Color resource: ColorPaper (#000000)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorPaper
        {
            get
            {
                if (_colorPaper == null)
                {
                    _colorPaper = Microsoft.Maui.Controls.Application.Current?.Resources["ColorPaper"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorPaper");
                }
                return _colorPaper;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _colorPrimary;
        /// <summary>
        /// Color resource: ColorPrimary (#889955)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorPrimary
        {
            get
            {
                if (_colorPrimary == null)
                {
                    _colorPrimary = Microsoft.Maui.Controls.Application.Current?.Resources["ColorPrimary"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorPrimary");
                }
                return _colorPrimary;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _colorPrimaryDark;
        /// <summary>
        /// Color resource: ColorPrimaryDark (#505A32)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorPrimaryDark
        {
            get
            {
                if (_colorPrimaryDark == null)
                {
                    _colorPrimaryDark = Microsoft.Maui.Controls.Application.Current?.Resources["ColorPrimaryDark"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorPrimaryDark");
                }
                return _colorPrimaryDark;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _colorPrimaryLight;
        /// <summary>
        /// Color resource: ColorPrimaryLight (#D4EE84)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorPrimaryLight
        {
            get
            {
                if (_colorPrimaryLight == null)
                {
                    _colorPrimaryLight = Microsoft.Maui.Controls.Application.Current?.Resources["ColorPrimaryLight"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorPrimaryLight");
                }
                return _colorPrimaryLight;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _colorSuccess;
        /// <summary>
        /// Color resource: ColorSuccess (#77DE27)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorSuccess
        {
            get
            {
                if (_colorSuccess == null)
                {
                    _colorSuccess = Microsoft.Maui.Controls.Application.Current?.Resources["ColorSuccess"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorSuccess");
                }
                return _colorSuccess;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _colorText;
        /// <summary>
        /// Color resource: ColorText (#E8E3D7)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorText
        {
            get
            {
                if (_colorText == null)
                {
                    _colorText = Microsoft.Maui.Controls.Application.Current?.Resources["ColorText"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorText");
                }
                return _colorText;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _colorTextButton;
        /// <summary>
        /// Color resource: ColorTextButton (#FFFFFF)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorTextButton
        {
            get
            {
                if (_colorTextButton == null)
                {
                    _colorTextButton = Microsoft.Maui.Controls.Application.Current?.Resources["ColorTextButton"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorTextButton");
                }
                return _colorTextButton;
            }
        }

        private static Microsoft.Maui.Graphics.Color? _colorTextSecondary;
        /// <summary>
        /// Color resource: ColorTextSecondary (#222233)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color ColorTextSecondary
        {
            get
            {
                if (_colorTextSecondary == null)
                {
                    _colorTextSecondary = Microsoft.Maui.Controls.Application.Current?.Resources["ColorTextSecondary"] as Microsoft.Maui.Graphics.Color
                        ?? throw new ColorResourceNotFoundException("ColorTextSecondary");
                }
                return _colorTextSecondary;
            }
        }

        #endregion

    }

    /// <summary>
    /// Fluent extension methods for working with colors
    /// </summary>
    public static class ColorExtensions
    {
        /// <summary>
        /// Creates a new color with the specified alpha/opacity value (0.0 to 1.0)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color WithAlpha(this Microsoft.Maui.Graphics.Color color, float alpha)
        {
            return color.WithAlpha(System.Math.Clamp(alpha, 0f, 1f));
        }

        /// <summary>
        /// Creates a new color with the specified opacity percentage (0 to 100)
        /// </summary>
        public static Microsoft.Maui.Graphics.Color WithOpacity(this Microsoft.Maui.Graphics.Color color, int percentage)
        {
            return color.WithAlpha(System.Math.Clamp(percentage / 100f, 0f, 1f));
        }

        /// <summary>
        /// Creates a lighter version of the color
        /// </summary>
        /// <param name="factor">Amount to lighten (0.0 to 1.0, default 0.2)</param>
        public static Microsoft.Maui.Graphics.Color Lighten(this Microsoft.Maui.Graphics.Color color, float factor = 0.2f)
        {
            factor = System.Math.Clamp(factor, 0f, 1f);
            return new Microsoft.Maui.Graphics.Color(
                color.Red + (1 - color.Red) * factor,
                color.Green + (1 - color.Green) * factor,
                color.Blue + (1 - color.Blue) * factor,
                color.Alpha);
        }

        /// <summary>
        /// Creates a darker version of the color
        /// </summary>
        /// <param name="factor">Amount to darken (0.0 to 1.0, default 0.2)</param>
        public static Microsoft.Maui.Graphics.Color Darken(this Microsoft.Maui.Graphics.Color color, float factor = 0.2f)
        {
            factor = System.Math.Clamp(factor, 0f, 1f);
            return new Microsoft.Maui.Graphics.Color(
                color.Red * (1 - factor),
                color.Green * (1 - factor),
                color.Blue * (1 - factor),
                color.Alpha);
        }

        /// <summary>
        /// Converts the color to a hex string (e.g., #FF5733)
        /// </summary>
        public static string ToHex(this Microsoft.Maui.Graphics.Color color)
        {
            return $"#{(int)(color.Red * 255):X2}{(int)(color.Green * 255):X2}{(int)(color.Blue * 255):X2}";
        }

        /// <summary>
        /// Converts the color to a hex string with alpha (e.g., #FF5733AA)
        /// </summary>
        public static string ToHexWithAlpha(this Microsoft.Maui.Graphics.Color color)
        {
            return $"#{(int)(color.Red * 255):X2}{(int)(color.Green * 255):X2}{(int)(color.Blue * 255):X2}{(int)(color.Alpha * 255):X2}";
        }

        /// <summary>
        /// Creates a Color from a hex string. Supports formats: #RGB, #RRGGBB, #AARRGGBB, RGB, RRGGBB, AARRGGBB
        /// </summary>
        /// <param name="hex">Hex color string with or without #</param>
        public static Microsoft.Maui.Graphics.Color FromHex(string hex)
        {
            if (string.IsNullOrWhiteSpace(hex))
                throw new System.ArgumentException("Hex string cannot be null or empty", nameof(hex));

            hex = hex.Trim().TrimStart('#');

            // Handle 3-digit shorthand (e.g., "RGB" -> "RRGGBB")
            if (hex.Length == 3)
                hex = $"{hex[0]}{hex[0]}{hex[1]}{hex[1]}{hex[2]}{hex[2]}";

            int alpha = 255;
            int red, green, blue;

            if (hex.Length == 6)
            {
                // RRGGBB
                red = System.Convert.ToInt32(hex.Substring(0, 2), 16);
                green = System.Convert.ToInt32(hex.Substring(2, 2), 16);
                blue = System.Convert.ToInt32(hex.Substring(4, 2), 16);
            }
            else if (hex.Length == 8)
            {
                // AARRGGBB
                alpha = System.Convert.ToInt32(hex.Substring(0, 2), 16);
                red = System.Convert.ToInt32(hex.Substring(2, 2), 16);
                green = System.Convert.ToInt32(hex.Substring(4, 2), 16);
                blue = System.Convert.ToInt32(hex.Substring(6, 2), 16);
            }
            else
            {
                throw new System.ArgumentException($"Invalid hex color format: {hex}. Expected 3, 6, or 8 characters.", nameof(hex));
            }

            return new Microsoft.Maui.Graphics.Color(red / 255f, green / 255f, blue / 255f, alpha / 255f);
        }

        /// <summary>
        /// Creates a Color from RGBA hex string. Supports formats: #RRGGBBAA, RRGGBBAA
        /// </summary>
        /// <param name="hex">RGBA hex color string with or without #</param>
        public static Microsoft.Maui.Graphics.Color FromHexRGBA(string hex)
        {
            if (string.IsNullOrWhiteSpace(hex))
                throw new System.ArgumentException("Hex string cannot be null or empty", nameof(hex));

            hex = hex.Trim().TrimStart('#');

            if (hex.Length != 8)
                throw new System.ArgumentException($"Invalid RGBA hex format: {hex}. Expected 8 characters (RRGGBBAA).", nameof(hex));

            int red = System.Convert.ToInt32(hex.Substring(0, 2), 16);
            int green = System.Convert.ToInt32(hex.Substring(2, 2), 16);
            int blue = System.Convert.ToInt32(hex.Substring(4, 2), 16);
            int alpha = System.Convert.ToInt32(hex.Substring(6, 2), 16);

            return new Microsoft.Maui.Graphics.Color(red / 255f, green / 255f, blue / 255f, alpha / 255f);
        }
    }
}
